Chart Modernization
docker-mailserver/docker-mailserver-helm pull request #90
Opened 2024-02-01 00:24 UTC by cfis

This is a follow up to https://github.com/docker-mailserver/docker-mailserver/issues/3825. While working through https://github.com/docker-mailserver/docker-mailserver-helm/pull/89, a made a number of changes to the chart in parallel. Thus ended up with a huge PR.

I realize its a lot of changes which can be overwhelming. In addition, they are NOT backwards compatible. The changes are summarized in the Chart readme as well as how to upgrade. To recap:

*  Update all dependencies (docker-mailserver, a bunch of github actions)
* Always create 4 PersistentVolumeClaims - mail-config, mail-state, mail-data, mail-log (previously just one was created). This matches what the docker container does from what I see
* Use `setup` instead of `setup.sh`. This removes a dependency on docker or podman and makes its clearer where config files go
*  Default to enabling rspamd
*  Enable rspamd ingress support
*  Enable dovecot full-text search
*  Removed cert-manager (you should set that up separately)
* Removed haproxy (you should set that up separately)
* Added full support for PROXY protocol, meaning if you enable it the chart will add new ports that are PROXY enabled 10465, 10587, 10993, 10995 while leaving the default ports untouched so they can be used by other apps in your Kubernetes cluster such as NextCloud, Gitlab, etc).

My plan is to work through the open PRs and issues once these changes have been merged.

2024-02-01 17:28 UTC, georglauterbach requested changes
Large diff, hence short comments from my side. I tried to cover everything, but with such a large PR, that's impossible. This PR would have been rejected in the main repo for being too big 😆😆😆 I appreciate the work you put into this, and the requested changes are not too big.

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/Chart.yaml
> +version: 2.3.1
Shouldn't this be `3.0.0`?

2024-02-01 17:28 UTC, georglauterbach commented on README.md
> +This repostitory contains a helm chart to deploy [Docker Mailserver](https://github.com/docker-mailserver/docker-mailserver) into a Kubernetes cluster. Docker Mailserver is a production-ready, fullst
The project's name is stylized as "docker-mailserver" (not "Docker Mailserver") - please do a global search-and-replace :)

I know, the main README of the project says "Docker Mailserver" - don't ask me why...

2024-02-01 17:28 UTC, georglauterbach commented on .github/workflows/on-push-lint-charts.yml
> +      - '.github/**'
The hyphens (`'`) around these strings are not required in YAML IIRC

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/Chart.yaml
> +dependencies: []
There is no newline at the end of this file, as GitHub's diff shows - intentional?

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/ci/ci-values.yaml
> +  # Needed to make kube-score happy
Please also state the reason kube-score needs this - otherwise, only you know the exact reason, which may be problematic for others looking at this chart

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/templates/NOTES.txt
> +    setup email add user@example.com password
Also possible:

```console
$ kubectl exec -it --namespace mail deploy/docker-mailserver -- setup email add user@example.com password
```

Just in case you want to change that, feel free to leave it as-is.

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/templates/configmap.yaml
> +    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
Just for me - what does `$` do here (and in the later lines)?

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/templates/deployment.yaml
> +              containerPort: 10587
Why not `submissions-proxy`? People like me who are used to the correct full names will later wonder why an abbreviation is used here. The same goes for `submission-proxy`.

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/README.md
> +Version 3.0 is not backwards compatible with previous versions. The biggest changes include:
Please consider using an empty line after a heading; I am very used to [MarkdownLint](https://github.com/DavidAnson/markdownlint), and it mandates newlines after headings, which I quite like. If you use VS Code with MD extensions, you should see some complaints there as well.

2024-02-01 17:28 UTC, georglauterbach commented on charts/docker-mailserver/values.yaml
> +      {{- if .Values.proxyProtocol.enabled }}
I didn't know one could use the TPL in `values.yaml` - or is this handled by Helm? I am confused why I see it `values.yaml` :D

2024-02-01 18:03 UTC, cfis commented on charts/docker-mailserver/Chart.yaml
> +version: 2.3.1
Yes (was leaving that to the end because I wasn't quite sure when versions have to be incremented for the ci/cd pipline to pass).

2024-02-02 03:32 UTC, cfis commented on README.md
> +This repostitory contains a helm chart to deploy [Docker Mailserver](https://github.com/docker-mailserver/docker-mailserver) into a Kubernetes cluster. Docker Mailserver is a production-ready, fullst
Done

2024-02-02 03:33 UTC, cfis commented on .github/workflows/on-push-lint-charts.yml
> +      - '.github/**'
Yeah, I've been casually removing extraneous quotes as I've seen them. Haven't decided if that is a good or bad idea?

2024-02-02 03:34 UTC, cfis commented on charts/docker-mailserver/Chart.yaml
> +dependencies: []
By product of removing the dependency on haproxy. Added a newline back.

2024-02-02 03:58 UTC, cfis commented on charts/docker-mailserver/ci/ci-values.yaml
> +  # Needed to make kube-score happy
Done

2024-02-02 04:06 UTC, cfis commented on charts/docker-mailserver/templates/NOTES.txt
> +    setup email add user@example.com password
Sure, added.

2024-02-02 04:10 UTC, cfis commented on charts/docker-mailserver/templates/configmap.yaml
> +    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
When executing a template you can pass it a scope. `.` is the current scope and `$` is the parent scope. Where this matters is inside `with` or `range` loops, where `.Values` is actually `$.Values`.  See https://helm.sh/docs/chart_template_guide/control_structures/#modifying-scope-using-with

2024-02-02 04:11 UTC, cfis commented on charts/docker-mailserver/templates/deployment.yaml
> +              containerPort: 10587
Yeah I would prefer that, but K8 only allows 15 characters in port names. https://stackoverflow.com/questions/73330773/is-there-any-way-to-disable-or-increase-port-name-length-in-kubernetes

2024-02-02 04:19 UTC, cfis commented on charts/docker-mailserver/README.md
> +Version 3.0 is not backwards compatible with previous versions. The biggest changes include:
Sure, just installed it, quite helpful!

2024-02-02 04:22 UTC, cfis commented on charts/docker-mailserver/values.yaml
> +      {{- if .Values.proxyProtocol.enabled }}
Ah - so the magic is here in the configmap.yaml template:

```
{{ tpl $config.data $ | indent 6 }}
```

`tpl`  is the `template` function - it treats any input as a template, even if it is coming from a values.yaml file. This is one of the tricks I used to remove the hard-coded config files from the chart. Instead, I moved them to values.yaml and templatized them. So now users can change them if needed.

Also note the scope parameter at the end is set to `$`.

See https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function

2024-02-02 04:25 UTC, cfis commented
Thanks for the review!

2024-02-02 04:25 UTC, merged

2024-02-02 08:40 UTC, georglauterbach commented on .github/workflows/on-push-lint-charts.yml
> +      - '.github/**'
In my personal repo for my infrastructure I actually lint against superfluous hyphens, so IMO it's a good idea 👍🏼

2024-02-02 08:41 UTC, georglauterbach commented on charts/docker-mailserver/templates/configmap.yaml
> +    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
Thanks! ☺️

2024-02-02 08:43 UTC, georglauterbach commented on charts/docker-mailserver/templates/deployment.yaml
> +              containerPort: 10587
Oh, I didn't know that 🙏🏼